### ISSUE TITLE
kitti loop closure demo launch file not working

### ISSUE THREAD

**Issue by Varun1407** [ethz-asl/segmatch#54] opened 2017-09-11 16:25 UTC
Hi all,

i am trying to execute the Kitti demo file as mentioned in the wiki page, but I am getting the following error.

--roslaunch laser_mapper kitti_loop_closure.launch
error -- [kitti_loop_closure.launch] is neither a launch file in package [laser_mapper] nor is [laser_mapper] a launch file name
The traceback for the exception was written to the log file

I have the launch files and bash setup accordingly, yet I am not able to execute. 
Kindly help.

Thanks in advance.

Varun Umesh

**Comment by rdube** [comment] 2017-09-12 05:48
Hi @Varun1407 thanks fo getting in touch! Did you follow the instructions of the readme file for compiling segmatch and laser_mapper?

**Comment by Varun1407** [comment] 2017-09-12 12:52
Hi @rdube. thanks for the response. Yes I followed all the instruction as per the read me file. Now I am getting an error as below.

[FATAL] [1505220674.695524262]: Error opening file: /home/eberhardt/segmatchcatkin_ws/src/segmatch/laser_mapper/demonstration_files/kitti/2011_09_30_drive_18.bag
[player-4] process has died [pid 3137, exit code 1, cmd /opt/ros/indigo/lib/rosbag/play -r 1 -s 0 --clock --pause /home/eberhardt/segmatchcatkin_ws/src/segmatch/laser_mapper/demonstration_files/kitti/2011_09_30_drive_18.bag __name:=player __log:=/home/eberhardt/.ros/log/0c484310-97b9-11e7-8644-3ca9f455f8e8/player-4.log].
log file: /home/eberhardt/.ros/log/0c484310-97b9-11e7-8644-3ca9f455f8e8/player-4*.log

I have converted the kitti dataset using the kitti to rosbag repository.

**Comment by rdube** [comment] 2017-09-12 13:31
You can get a bag file here: http://robotics.ethz.ch/segmatch/ and make sure that it is in the correct location.

**Comment by Varun1407** [comment] 2017-09-12 16:12
I used the file you suggested but still I am getting the same error. 
I have placed it in the location as specified in the wiki for demonstrations of segmatch.

**Comment by rdube** [comment] 2017-09-13 09:35
Most likely the file was not found. Can you recheck the path? eg. is the segmatchcatkin_ws folder correct?

**Comment by rdube** [comment] 2017-09-13 09:36
Simply go to the folder where `2011_09_30_drive_18.bag` is located and do pwd to get the correct path.

**Comment by Varun1407** [comment] 2017-10-03 17:40
I rectified the previous error. but now i am facing a new one.
[laser_mapper-2] process has died [pid 30749, exit code -11, cmd /home/eberhardt/segmatchcatkin_ws/devel_isolated/laser_mapper/lib/laser_mapper/laser_mapper_node __name:=laser_mapper __log:=/home/eberhardt/.ros/log/40989b54-a85f-11e7-989b-3ca9f455f8e8/laser_mapper-2.log].
log file: /home/eberhardt/.ros/log/40989b54-a85f-11e7-989b-3ca9f455f8e8/laser_mapper-2*.log
 Kindly help to resolve this.

thanks.

**Comment by rdube** [comment] 2017-10-09 14:25
@Varun1407 I believe that the issue is not related to the launch file anymore (or of not having the bag file at the correct location). Please consider closing and re-opening new issues when a given problem is fixed. 

For this new issue you could use GBD to get more information. See #47

**Comment by rdube** [comment] 2017-10-19 06:23
@Varun1407 did that help?

**Comment by rdube** [comment] 2017-11-28 08:32
@Varun1407 given the delay I will assume that this has been solved on your side by now.

**Closed by rdube** 2017-11-28 08:32 UTC
