### ISSUE TITLE
Unable to publish trajectory when executing kitti localization example

### ISSUE THREAD

**Issue by kurogane1031** [ethz-asl/segmatch#57] opened 2017-10-25 10:01 UTC
Hi all
I am following the example from the following link, https://github.com/ethz-asl/segmatch/wiki/Demonstrations.

However no trajectory was published. May I know any possible method for me to work out on this issue?

the following are the logs during roslauch. 
Additional note: the loop closure example also having similar issues.
thank you in advance

> I1025 16:06:01.768736 23467 incremental_estimator.cpp:54] Loading ICP configurations from: /home/user/catkin_ws4/src/segmatch/laser_mapper/launch/kitti/icp_dynamic_outdoor.yaml
inverted_max_eigen_double_ 39702.091084   Duration: 34.098621 / 137.842093     
0.000401043 5.35673e-06 5.30817e-06     3.02663 5.30819e-06    0.917515      1.0013
inverted_max_eigen_float_ 
0.000401043 5.35673e-06 5.30817e-06     3.02663 5.30819e-06    0.917515      1.0013
[ INFO] [1508918761.815895548]: Loading target cloud.
I1025 16:06:01.815948 23467 common.hpp:135] Loading cloud: /home/user/catkin_ws4/src/segmatch/laser_mapper/demonstration_files/kitti/drive27_target_map.pcd.
Failed to find match for field 'intensity'.uration: 52.858947 / 137.842093     
I1025 16:06:20.684986 23467 euclidean_segmenter.cpp:28] Starting euclidean segmentation.
I1025 16:06:34.345943 23467 euclidean_segmenter.cpp:42] Segmentation complete. Took 13661.5ms and found 1026 clusters.
I1025 16:06:34.354141 23467 segmatch.cpp:149] Removing too near segments from source map.
I1025 16:06:34.354260 23467 segmatch.cpp:844] segment_ids.size() 1026
I1025 16:06:34.356477 23467 segmatch.cpp:919] Removed 19 duplicate segments in 2.799 ms.
I1025 16:06:34.387974 23467 descriptors.cpp:61] Decriptor 0 took 31.962 ms.
[laser_mapper-3] process has died [pid 23467, exit code -11, cmd /home/user/catkin_ws4/devel/lib/laser_mapper/laser_mapper_node __name:=laser_mapper __log:=/home/user/.ros/log/2bce1b92-b95b-11e7-bd94-88d7f69239dd/laser_mapper-3.log].
log file: /home/user/.ros/log/2bce1b92-b95b-11e7-bd94-88d7f69239dd/laser_mapper-3*.log
[laser_mapper-3] restarting process
process[laser_mapper-3]: started with pid [23637]
WARNING: Logging before InitGoogleLogging() is written to STDERR137.842093     
I1025 16:06:35.216768 23637 segmatch.cpp:18] Do not forget to initialize SegMatch.
I1025 16:06:35.257854 23637 laser_track.cpp:16] Loading ICP configurations from: /home/user/catkin_ws4/src/segmatch/laser_mapper/launch/kitti/icp_dynamic_outdoor.yaml
I1025 16:06:35.258607 23637 laser_track.cpp:26] Loading ICP input filters from: /home/user/catkin_ws4/src/segmatch/laser_mapper/launch/kitti/input_filters_outdoor.yaml
I1025 16:06:35.258886 23637 laser_track.cpp:48] Creating ICP noise model with cauchy.
I1025 16:06:35.258913 23637 incremental_estimator.cpp:31] Creating loop closure noise model with cauchy.
I1025 16:06:35.258924 23637 incremental_estimator.cpp:54] Loading ICP configurations from: /home/user/catkin_ws4/src/segmatch/laser_mapper/launch/kitti/icp_dynamic_outdoor.yaml
inverted_max_eigen_double_ 39735.572313   Duration: 67.579851 / 137.842093     
0.000401043 5.35673e-06 5.30817e-06     3.02663 5.30819e-06    0.917515      1.0013
inverted_max_eigen_float_ 
0.000401043 5.35673e-06 5.30817e-06     3.02663 5.30819e-06    0.917515      1.0013
[ INFO] [1508918795.309016166]: Loading target cloud.
I1025 16:06:35.309072 23637 common.hpp:135] Loading cloud: /home/user/catkin_ws4/src/segmatch/laser_mapper/demonstration_files/kitti/drive27_target_map.pcd.
[visualizer-2] process has finished cleanlyuration: 86.846634 / 137.842093     
log file: /home/user/.ros/log/2bce1b92-b95b-11e7-bd94-88d7f69239dd/visualizer-2*.log
Failed to find match for field 'intensity'.uration: 87.259952 / 137.842093     
I1025 16:06:55.101943 23637 euclidean_segmenter.cpp:28] Starting euclidean segmentation.
[player-4] killing on exit639760.433020   Duration: 92.440558 / 137.842093     
[laser_mapper-3] killing on exit

**Comment by rdube** [comment] 2017-10-27 08:29
Hi @kurogane1031 did you kill the laser_mapper node yourself? ([laser_mapper-3] killing on exit)

Otherwise it looks like the segmentation of the target map was not finished (Starting euclidean segmentation). Did you modify the launch scripts or start playing the bag directly after running roslaunch? 

You need to give your computer some time to segment the target map before starting the bag. When this is completed you should see the target map being displayed in rviz. Did you get to see that?

**Comment by kurogane1031** [comment] 2017-10-27 10:20
hi @rdube , thanks for the reply. I didnt modify any of script. Furthermore, I waited for
> I1025 16:06:34.345943 23467 euclidean_segmenter.cpp:42] Segmentation complete. Took 13661.5ms and found 1026 clusters.
to be displayed in the terminal and the map to be published in RVIZ.

Only when these was done then i pressed the space bar to start the rosbag

The laser_mapper isnt killed by me, instead, it is automatic during running process and somehow repeating the similar loop, i.e: laser_mapper killed, then the laser_mapper restarting and killed again, and restarting until the bag finished playing.

**Comment by rdube** [comment] 2017-11-09 14:04
@kurogane1031 you might get more information about this error by using GBD (see #47). Did you follow the instructions for building? I just rebuilt everything from scratch and I do get the trajectories being published.

The restarting is caused by respawn being set to true in the launch files.

**Comment by rdube** [comment] 2018-02-04 11:49
@kurogane1031 I will close this issue feel free to re-open if it is relevant!

**Closed by rdube** 2018-02-04 11:49 UTC
